### ISSUE TITLE
Metadata standard for electrode materials

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/electrochemistry-metadata-schema#4]
# Draft

Currently, the entries for the working electrode are not very useful

```yaml
working electrode:
    material: Ni
    crystallographic orientation: 111 # hkl, 100, 110, poly
```

Maybe we can go with something like this for a simple single crystal.

```yaml
working electrode:
      type: singlecrystal
      component:
          - name: Ni
            type: singlecrystal
            role: subsrate # I am not happy with role. Function would also sound odd.
            crystallographic orientation: '111' # hkl, 100, 110, poly
```

This becomes already complex for other singlecrystal cases, such as:

* Metals deposited on a singlecrystal Pt/Ru(0001)
* Surface confined alloys PtxRuy/Ru(0001)
* Near-surface alloys (NSA) - Alloy in the topmost layers PtRu/Ru(00001)-NSA
* Bulk alloys PtRu(111)
* ...

Maybe we should see if there is a standard for such materials in other repositories linked to the [NFDI initiative](https://www.nfdi.de/?lang=en) such as FAIRMAT, NFDI4Cat or Kadi4mat

## Random links

[Battery material metdadata standard](https://www.nature.com/articles/s41597-020-00602-2)
